baseURL = "https://etw.ooo/"
languageCode = "en-us"
title = "Eric Woo"
theme = "m10c"

[params]
  avatar = "avatar.svg"
  author = "Eric Woo"

[[params.social]]
  icon = "gitlab"
  name = "My GitLab"
  url = "https://gitlab.com/ewoo"
