baseURL = "https://etw.ooo/"
languageCode = "en-us"
title = "Eric Woo"
theme = "m10c"

[params]
  avatar = "avatar.svg"
  author = "Eric Woo"
  description = "sleep, dream, move"

[[params.social]]
  icon = "gitlab"
  name = "gitlab"
  url = "https://gitlab.com/ewoo"
